const BRAND = `${import.meta.env.BASE_URL}brand/`

type RixLogoVariant = 'horizontal' | 'mark' | 'stacked'

interface RixLogoProps {
  /** Sets the height; the width follows the artwork. e.g. "h-6 w-auto". */
  className?: string
  /**
   * `horizontal` — mark + RIX, for the sidebar and the project toolbar.
   * `mark` — the R on its own, where there's no room for the words.
   * `stacked` — the full lockup with the tagline, for About and startup.
   */
  variant?: RixLogoVariant
}

/**
 * The RiX lockup, drawn from the brand artwork in `public/brand/` (generated by
 * scripts/build-brand-assets.py — see brand/README.md).
 *
 * Every asset is the light-ink cut, so these only read on a dark surface, which
 * is the whole app. On a light background use `rix-lockup-light` instead; it
 * isn't wired up here because nothing in the app needs it yet.
 *
 * The artwork is two-colour — white ink plus the gold accent — so unlike the
 * wordmark this replaced, it can't inherit `currentColor`. Callers set the
 * height and nothing else.
 */
export function RixLogo({ className = 'h-6', variant = 'horizontal' }: RixLogoProps) {
  if (variant === 'mark') {
    return <img src={`${BRAND}rix-mark.png`} srcSet={`${BRAND}rix-mark.png 1x, ${BRAND}rix-mark@2x.png 2x`} alt="RiX" className={className} draggable={false} />
  }

  if (variant === 'stacked') {
    return <img src={`${BRAND}rix-lockup.png`} srcSet={`${BRAND}rix-lockup.png 1x, ${BRAND}rix-lockup@2x.png 2x`} alt="RiX — Film Studio in a Box" className={className} draggable={false} />
  }

  // Composed rather than baked so the two halves can be optically balanced: the
  // wordmark sits at 56% of the mark's height, which lines its cap height up
  // with the body of the R.
  return (
    <div className={`inline-flex items-center gap-1.5 ${className}`} role="img" aria-label="RiX">
      <img src={`${BRAND}rix-mark.png`} srcSet={`${BRAND}rix-mark.png 1x, ${BRAND}rix-mark@2x.png 2x`} alt="" className="h-full w-auto" draggable={false} />
      <img src={`${BRAND}rix-wordmark.png`} srcSet={`${BRAND}rix-wordmark.png 1x, ${BRAND}rix-wordmark@2x.png 2x`} alt="" className="h-[56%] w-auto" draggable={false} />
    </div>
  )
}
